server:
  shutdown: graceful

spring:
  application:
    name: coupon-api
  profiles:
    active: dev # 프로파일 활성화
  lifecycle:
    timeout-per-shutdown-phase: 30s

#    datasource:
#      url: jdbc:mysql://133.186.241.167:3306/nhn_academy_21?useSSL=false&serverTimezone=UTC
#      username: nhn_academy_21
#      password: oMyVE2dkskrCXF
#      driver-class-name: com.mysql.cj.jdbc.Driver
  #  datasource:
  #    url: jdbc:h2:mem:bookstore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # ??? ?? ???? ??????. ?? JPA ???? ?????? ??? ?? ?? ?????? ?, ?????? ??? ???? ??? ?????.



#  h2:
#    console:
#      enabled: true
#      path: /h2-console

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

#nhncloud:
#  storage:
#    url: https://kr1-api-object-storage.nhncloudservice.com/v1/AUTH_c20e3b10d61749a2a52346ed0261d79e
#    token: gAAAAABnc0U-kqIfK374SJuoxNAIptX16ELrdHz-WtL0EDwNO4Gha-9pHHoLTKqsu2a_yvPHkQq-SoAXkBLq_Anfoeu4Uz77uBB365-ySzOoEqdcjYtyW_hivK8h8OqRDHpMXA0Uaj02YBSzPVbIaE3dEXxzgCGeZRf9cg2O0Q3SUOXG-2-RGRo
#    container: aurora # 컨테이너 이름


  #logging:
  #  level:
  #    root: debug
  #    org.hibernate.orm.jdbc.bind: trace
  #    org.springframework.transaction.interceptor: trace
  #
  #    sun.rmi: WARN
  #    javax.management: WARN

  ### key manager
#  key:
#    manager:
#      url: https://api-keymanager.nhncloudservice.com
#      path: /keymanager/v1.0/appkey/{app-key}/secrets/{key-id}
#      app-key: qTQNj7LyHhdAazH3
#      password: 5555