server:
  port: 8480

  spring:
    datasource:
      url: jdbc:mysql://133.186.241.167:3306/nhn_academy_21?useSSL=false&serverTimezone=UTC
      username: nhn_academy_21
      password: oMyVE2dkskrCXF
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
  #    username: root
  #    password: 3489
  #    driver-class-name: com.mysql.cj.jdbc.Driver