name: Java CI with Maven

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install custom JAR
      run: |
        mvn install:install-file \
          -Dfile=libs/toast-logncrash-logback-sdk-3.0.5.jar \
          -DgroupId=com.toast.java.logncrash.logback \
          -DartifactId=logncrash-java-sdk3 \
          -Dversion=3.0.5 \
          -Dpackaging=jar

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run SonarQube
      run: mvn clean verify sonar:sonar -Dsonar.projectKey=5rora-book-shop -Dsonar.projectName='5rora-book-shop' -Dsonar.host.url=${{secrets.SONAR_HOST}} -Dsonar.token=${{secrets.SONAR_TOKEN}}

    - name: Set up SSH key and add passphrase
      run: |
        mkdir -p ~/.ssh  # .ssh 디렉토리 생성
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"  # ssh-agent 실행
        echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

    - name: Upload file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "target/*.jar"
        target: "~/"
        rm: false

    - name: Execute shell script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: "./startup-coupon.sh"
